template = ShipTemplate():setName("EscortMe"):setClass("Simulation", "Basic"):setModel("transport_1_1")
template:setHull(100)
template:setShields(50, 50)
template:setSpeed(100, 6, 10)
template:setRadarTrace("radar_transport.png")
